### ISSUE TITLE
are you sure we don't need nginx configuration?

### ISSUE THREAD

**Issue by gmmurugan** [anuriq/chef-kibana5#6]

**Comment by anuriq** [comment]
Hi @gmmurugan 
My original intention was to provide resources/recipes for configuration of nginx, apache, etc. But then 2 things came to my mind:
* nginx configuration part and attributes in the cookbook became larger than kibana part. this is strange because this is a cookbook for kibana
* it contradicts unix philosophy about making one thing.

There is an example of configuration alongside nginx in `test/fixtures`. As you can see, it is a lot cleaner this way, when we do just kibana part, and nginx part is done by `chef_nginx` for example.

**Comment by anuriq** [comment]
anyway, thanks for suggestion.
